### ISSUE TITLE
Rebase to official Fedora Docker image

### ISSUE THREAD

**Issue by kwizart** [scaleway/image-fedora#32]
Please try to rebase to the official Fedora docker image:
dl.fedoraproject.org/pub/fedora/linux/releases/24/Docker/armhfp/images/
(and soon the 25 version)...

**Comment by kwizart** [comment]
FYI There is an issue for this image to be published because how alternates arches are handled by docker hub.

**Comment by frafra** [comment]
Yay! F25 would be great :)

**Comment by seuf** [comment]
Fedora 26 is out now, and still no fedora image available for VC1 Scaleway instances. Do you have an ETA for releasing a fedora x86_64 image ?

**Comment by itamarjp** [comment]
I am interested in having Fedora 27 available, please do something, thank you.

**Comment by halmartin** [comment]
@kwizart 

Our new Fedora 27 images are based on the official Docker Hub image available here: https://hub.docker.com/_/fedora/

Due to limited resources, we are focusing on providing Fedora 27 only for `VC1` and `C2` instances right now.

---
@itamarjp @seuf 

The Fedora 27 image for `VC1` instances was released this week.
