### ISSUE TITLE
systemd-journald fails to restart without regenerating /etc/machine-id after first boot

### ISSUE THREAD

**Issue by vrischmann** [scaleway/image-fedora#40]
Hi,

I'm provisioning a START1-S server with Fedora 28.

At first login this is the state of journald:

    # ps aux | grep journald
    root       292  0.0  0.6  91512 12924 ?        Ss   22:17   0:00 /usr/lib/systemd/systemd-journald
    root      1049  0.0  0.0   9144  1052 pts/0    S+   22:26   0:00 grep --color=auto journald
    # journalctl
    No journal files were found.
    -- No entries --
    # systemctl status systemd-journald
    ● systemd-journald.service - Journal Service
       Loaded: loaded (/usr/lib/systemd/system/systemd-journald.service; static; vendor preset: disabled)
       Active: active (running) since Sat 2018-06-23 22:17:46 UTC; 9min ago
         Docs: man:systemd-journald.service(8)
               man:journald.conf(5)
     Main PID: 292 (systemd-journal)
       Status: "Processing requests..."
        Tasks: 1 (limit: 2343)
       Memory: 8.8M
       CGroup: /system.slice/systemd-journald.service
               └─292 /usr/lib/systemd/systemd-journald
    # systemctl restart systemd-journald
    Job for systemd-journald.service failed because the control process exited with error code.
    See "systemctl status systemd-journald.service" and "journalctl -xe" for details.

From now on journald is dead and can't be restarted.

To make it work I need to do this:

    # systemd-machine-id-setup
    Initializing machine ID from random generator.
    # systemctl restart systemd-journald
    # systemctl status systemd-journald
    ● systemd-journald.service - Journal Service
       Loaded: loaded (/usr/lib/systemd/system/systemd-journald.service; static; vendor preset: disabled)
       Active: active (running) since Sat 2018-06-23 22:29:00 UTC; 4s ago
         Docs: man:systemd-journald.service(8)
               man:journald.conf(5)
     Main PID: 1071 (systemd-journal)
       Status: "Processing requests..."
        Tasks: 1 (limit: 2343)
       Memory: 4.7M
       CGroup: /system.slice/systemd-journald.service
               └─1071 /usr/lib/systemd/systemd-journald
    Jun 23 22:29:00 scw-f3c8e0 systemd-journald[1071]: Journal started
    Jun 23 22:29:00 scw-f3c8e0 systemd-journald[1071]: System journal (/var/log/journal/3918da67d9ae4fa1843df292ed61559e) is 8.0M, max 4.0G, 3.9G free.
    Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
    # journalctl -n 1
    -- Logs begin at Sat 2018-06-23 22:29:00 UTC, end at Sat 2018-06-23 22:29:00 UTC. --
    Jun 23 22:29:00 scw-f3c8e0 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:kernel_t:s0 msg='unit=systemd-journald comm="systemd" exe="/usr/lib/systemd/systemd" hostname=

At first login, the `/etc/machine-id` contains a UUID (formatted with the -, like `73618885-dfe7-47c9-959f-26ad21223e4b`); after calling `systemd-machine-id-setup` the machine-id doesn't contain any -
I'm guessing systemd doesn't like the first format for some reason.

Either way, it's a little annoying having no working logs by default.

**Comment by gombosg** [comment]
Same issue here. Thanks for the solution!

**Comment by vrischmann** [comment]
Yeah, my guess is the VMs are based on KVM. `systemd-machine-id-setup` says this in the man page:

    2. If run inside a KVM virtual machine and a UUID is configured (via the -uuid option), this UUID is used to initialize the machine ID. The caller must ensure that the UUID passed is sufficiently
           unique and is different for every booted instance of the VM.

Why journald doesn't work after that I have no idea.

**Comment by gombosg** [comment]
AFAIK it's because this is not according to the standard [machine ID](http://man7.org/linux/man-pages/man5/machine-id.5.html).

It shouldn't contain any dashes.

> The machine ID is a single newline-terminated, hexadecimal, 32-character, lowercase ID.
> ...
>  This machine ID adheres to the same format and logic as the D-Bus machine ID.

The [machine-id manual](http://man7.org/linux/man-pages/man5/machine-id.5.html) tells exactly the same.

If you enter `journalctl --new-id128` it prints these IDs in different formats:
```bash
~ $ journalctl --new-id128 
As string:
ba3834ef03e44fbbbc97a863d9b876ae

As UUID:
ba3834ef-03e4-4fbb-bc97-a863d9b876ae

As man:sd-id128(3) macro:
#define MESSAGE_XYZ SD_ID128_MAKE(ba,38,34,ef,03,e4,4f,bb,bc,97,a8,63,d9,b8,76,ae)

As Python constant:
>>> import uuid
>>> MESSAGE_XYZ = uuid.UUID('ba3834ef03e44fbbbc97a863d9b876ae')
```

Hmmm...😕 As you can see, only the first one fits the description above. So we can say that this is not a journalctl bug. It could be a systemd-machine-id-setup bug though. Or is it just this particular image, or the Scaleway setup scripts?

**Comment by gombosg** [comment]
Okay so this UUID is generated here in the [Dockerfile](https://github.com/scaleway/image-fedora/blob/3a1bc616fd9126aa4bb65ac605221cff5232c3cf/28/Dockerfile#L38) with `scw-gen-machine-id`.
Which can be found [here](https://github.com/scaleway/image-tools/blob/b90a2b06f813c14b6026f20ef0b6f6358a415419/bases/overlay-openrc/etc/init.d/scw-gen-machine-id) if I'm correct.

And on [line 15](https://github.com/scaleway/image-tools/blob/b90a2b06f813c14b6026f20ef0b6f6358a415419/bases/overlay-openrc/etc/init.d/scw-gen-machine-id#L15):
`        uuidgen >/etc/machine-id`
Which generates an UUID with dashes:
```bash
~ $ uuidgen
6dc8f770-54a2-4835-9411-961de2b15384
```
According to the machine-id manual this 

- is not according to the standard machine ID format
- overwrites KVM UUIDs - even not setting this file up at all would be better (when it just auto-generates some UUID)
- is not good practice since [`dbus-uuidgen`](https://dbus.freedesktop.org/doc/dbus-uuidgen.1.html) should be used.


What do you think? Should we issue a bug report there at [scaleway image tools](https://github.com/scaleway/image-tools/issues)?

**Comment by vrischmann** [comment]
Nice debugging. I think the script is more likely [this one](https://github.com/scaleway/image-fedora/blob/master/28/overlay-image-tools/usr/local/sbin/scw-gen-machine-id) than the one from openrc. 
However it's essentially the same so your analysis looks correct.

**Comment by nlm** [comment]
I quickly fixed this in https://github.com/scaleway/image-fedora/commit/931c65e37a4460a335b4f845f666c78f0640a2ab, as this is more correct in any case, but i'm currently evaluating the possibility to use `systemd-machine-id-setup` instead

**Comment by gombosg** [comment]
@nlm thanks for the fix! Yes, I think in this case, `systemd-machine-id-setup` is safe, because it tries to [read](https://github.com/systemd/systemd/blob/ca285cdb405f99ba6c67d8e8da263b7bbb52c19f/src/core/machine-id-setup.c#L38) machine UUIDS using [`id128-read`](https://github.com/systemd/systemd/blob/b0450864f1723ad12176d7956377d89ff4a84d8c/src/libsystemd/sd-id128/id128-util.c#L82) which, using `sd_id128_from_string` always [skips dashes](https://github.com/systemd/systemd/blob/b0450864f1723ad12176d7956377d89ff4a84d8c/src/libsystemd/sd-id128/sd-id128.c#L38)!  😉
